build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  paths:
    - "src/*"
  excluded_paths:
    - "vendor/*"
    - "var/*"
    - "tests/*"

checks:
  php: true
